# Streamlit Cloud Secrets Template
# Copy this content to Streamlit Cloud secrets section

# OAuth2 Credentials (your oauth2_credentials.json content)
[oauth2_credentials]
type = "installed"
client_id = "your_client_id_here"
client_secret = "your_client_secret_here"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
redirect_uris = ["urn:ietf:wg:oauth:2.0:oob", "http://localhost"]

# Service Account Credentials (your google_credentials.json content - optional backup)
[service_account]
type = "service_account"
project_id = "your_project_id"
private_key_id = "your_private_key_id"
private_key = "your_private_key"
client_email = "your_service_account_email"
client_id = "your_client_id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"